---
- name: Workflow node reproducer
  hosts: all
  gather_facts: false

  tasks:

    - name: Include child1
      ansible.builtin.include_tasks:
        file: tasks/child1.yml
      run_once: true

    - name: Include child2
      ansible.builtin.include_tasks:
        file: tasks/child2.yml
      run_once: true
