---
- name: Workflow node reproducer
  hosts: all
  gather_facts: false

  tasks:

    - name: Show all hosts in the play
      ansible.builtin.debug:
        msg:
          - "inventory_hostname={{ inventory_hostname }}"
          - "ansible_play_hosts={{ ansible_play_hosts }}"
          - "ansible_play_hosts_all={{ ansible_play_hosts_all }}"

    - name: Include child1
      ansible.builtin.include_tasks:
        file: tasks/child1.yaml
      run_once: true

    - name: Include child2
      ansible.builtin.include_tasks:
        file: tasks/child2.yaml
      run_once: true
